### ISSUE TITLE
Start doing a pure Java 8 test in Travis

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1044]
We are noticing that there are significant differences between Java 7 and Java 8, such that we need to verify that BRJS actually works when used with Java 8 instead of Java 7.

**Comment by james-shaw-turner** [comment]
We need to increase the priority on this. Oracle will stop public patches on Java after April. The auto-update process is already doing this automatically.  see http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by andyberry88** [comment]
This is fixed in https://github.com/BladeRunnerJS/brjs/pull/1314 which has just been merged. We now have a Java7 and Java8 CI loop in Travis.
