### ISSUE TITLE
base tag breaks links in single page apps

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs#1059]
Since we have a base tag which goes up on directory any relative links for routes in single page apps actually reload the page because the link goes to a different page.

![screen shot 2014-11-10 at 19 02 02](https://cloud.githubusercontent.com/assets/328367/4981770/5429660c-690c-11e4-90c7-c75295ca54bd.png)

If this is something we have to put up with, what is the solution? Hard-coding the locale into the `href` doesn't feel right.

**Comment by dchambers** [comment]
This should be fixed by #1173.

**Comment by thecapdan** [comment]
We are looking at an issue with this PR that causes an app to be redirected to the login page when you try to login. Will move back to dev for now....

**Comment by thanhc** [comment]
This has been tested and verified by adding an anchor tag to index.html and ensuring that page is not reloaded, tested with both single and multi locale apps
