### ISSUE TITLE
[feature] App level alias override

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1071]
I would like to be able to define an alias override that would apply to everything in the app (aspects, workbenches & tests). With the option to further override (as you can now) on workbench/test level.

Right now I have to copy the same alias override (in `aliases.xml`) to a lot of different places in my app.

**Comment by andyberry88** [comment]
This was largely complete when I picked up it. I've added tests for groups and scenarios. @thecapdan can you do your thing and do some exploratory testing?

**Comment by thecapdan** [comment]
I think we need to update the docs to demonstrate how to use this new feature, maybe here: http://bladerunnerjs.org/docs/use/ioc/

**Comment by thecapdan** [comment]
The spec tests for this are a little unclear - so we should tidy those up + I'll add an example in the it-app

**Comment by thecapdan** [comment]
"With the option to further override (as you can now) on workbench/test level." I assume this means we have app level aliases that we would like to optionally override at the test level. did we decide how this was going to be done, if so, can we document it

**Comment by thecapdan** [comment]
Moving back to dev.

1. needs acceptance criteria in the description
2. when i add an aliases.xml with an alias defined at the app level, i am unable to use that alias in App.js. (I can add this test case to the it-app)

**Comment by andyberry88** [comment]
While looking at whether we had a test case for the issue @thecapdan described above I noticed
a. we don't have a test for this, so we need to add one for this scenario and any related scenarios
b. some of the tests are badly named: `aliasDefinitionsInAspectAreOverridenByTheAppAliases` isn't the behaviour we expect and what the test is actually testing. This should be something like `aliasDefinitionsInAspectOverrideAppAliases`.

This needs a lot more work.

**Comment by thecapdan** [comment]
retested. working now. + overriding the app level alias in the default aspect works as expected.

needs release note, but will merge anyway because im a soft touch
