### ISSUE TITLE
move all API classes into an org.bladerunnerjs.api package and review the Plugin APIs

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1085]
We need to make it obvious which classes are part of our API and ensure they don't change between releases.
As part of this we should make sure the APIs are reasonable before a 1.0 release and review the class/method accessibility.

**Comment by andyberry88** [comment]
#1192 contains the `move all API classes into an org.bladerunnerjs.api package` changes. `review the Plugin APIs` part will done in a separate PR taken from the #1192 branch.

**Comment by andyberry88** [comment]
#1277 contains the `review plugin APIs part of this`.

**Comment by ccpetercc** [comment]
I've spotted an issue on develop which occurs when requiring a file for the first time without restarting BRJS. This causes the require to fail.

To recreate 
- create a brjs App.
- Create a new js file in the default-aspect src directory
- Do not require the file anywhere in the app
- run ./brjs serve
- Navigate to the app's URL - it runs successfully
- Add a require statement to App.js to import the js file created in the second step
- Refresh the app's URL - exceptions will be thrown on the client complaining that no definition for the module is found.

If BRJS is restarted, then the exceptions stop

This works on release v0.15.4
