### ISSUE TITLE
Log a warning when CommonJs tests aren't wrapped within an IIFE

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1091]
Any `require()` invocations that occur outside of an IIFE cause global pointers to modules to be created, which is at odds with the [sub-realms](https://github.com/BladeRunnerJS/browser-modules#sub-realms) feature, and will lead to bugs.

When we create the JSTD bundles we should check each file inside `tests`, if the first line doesn't match an IIFE regex log a warning.

**Comment by thecapdan** [comment]
This was QAd by my QA intern @dchambers

**Comment by dchambers** [comment]
Sorry @thecapdan, guilty as charged!
