### ISSUE TITLE
Make the HTML resource service work for all known use cases

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1116]
We've changed `BRHtmlResourceService` a number of times to fix bugs, where each time it's caused some other problems. We need to understand the complete set of use-cases and issues that need to be addressed, and tackle this holistically. This issue should be used to collate all of this information in one place before we contemplate making any changes.

The _resource-service_ should:

  * Allow the developer to place templates within a `<template/>` tag, but continue to support arbitrary tags with an `id` attribute.
  * Allow any tag to be used as the top-level node (e.g. `<td>`) and still work on IE8.
  * Place the templates within a `<template/>` tag on browsers where this is supported, so that web components can be used.
  * Provide a clone of the template when `getHtmlTemplate()` is invoked (rather than relying on Presenter or Knockout to do this).

Additionally, the _resource-service_ should continue to support the following use cases:

  * We should be able to support templates that have been defined within a `<script/>` tag.
  * We should be able to support templates that contain non-standard (e.g. HTML5) tags.
  * Templates should't be added to the document, or should be added in a way that won't interfere with any web application.

**UPDATE -- FINAL PLAN:**

Mandatory Changes:

  1. The BRJS server will be modified to allow templates to be provided within `<template/>` tags, and to wrap templates that aren't provided within `<template/>` tags, so that all templates provided to the client are wrapped within `<template/>` tags.
  1. In conjuction within the above change, the `HTMLResourceService` will be modified to return a fresh _document-fragment_ of the template contents, rather than providing a single template element (and re-using the same element each time at that).

Optional Post 1.0 Changes:

  1. An optional `<@brjs-templates@>` tag could be made available that can be used to load the HTML templates within the page itself, rather than requiring a separate XHR request.
  1. The `HTMLResourceService` could then be modified to detect if the templates have been pre-loaded, and use these directly instead of loading via XHR.
  1. IE8 support for nested `<td>` elements, etc, could be provided by using a JavaScript HTML parser to convert the `innerHTML` returned for each `<template/>` tag into a `DocumentFragment` instance.

This plan meets all of the originally stated goals, plus one more:

  1. It allows templates that contain more than one element to be created.

Though it does have one minor downside:

  1. `<img>` tags within templates will load the images in the background in IE, though we almost never use `<img>` tags since they are inconvenient to use in BRJS.

**Comment by dchambers** [comment]
I was hoping to use a template polyfill, but learned that:

  1. Even the latest versions of IE [don't natively support templates](http://caniuse.com/#feat=template).
  1. The only comprehensive template polyfill is made available within [webcomponentsjs](https://github.com/WebComponents/webcomponentsjs), which is part of a much bigger polyfill, and weighs in at 108K minified.
  1. Although the [webcomponentsjs](https://github.com/WebComponents/webcomponentsjs) project provides smaller polyfills for every other aspect of the Web Components umbrella technology, they are [unable to provide a separate template polyfill](https://github.com/webcomponents/webcomponentsjs/issues/45) since it relies on all constituent features.
  1. There is a [minimal template polyfill in JsFiddle](http://jsfiddle.net/brianblakely/h3EmY/) which works, but which doesn't cause the template contents to be inert in IE, so that, for example, images are downloaded when they shouldn't be.
  1. The best fallback option is therefore an [overloaded script tag](http://www.html5rocks.com/en/tutorials/webcomponents/template/#toc-overloadingscript).
  1. Feature detection of [native template support](http://www.html5rocks.com/en/tutorials/webcomponents/template/#toc-detect) is simple to perform.

Since we'd prefer to use native `<template/>` tags in browsers that support them, the `BRHtmlResourceService` should be converted into a proxy class, that delegates all method invocations to an inner `HtmlResourceService` instance, being either `NativeHtmlResourceService` or `FallbackHtmlResourceService` depending on the browser's capabilities.

**Comment by dchambers** [comment]
Alternatively, we might also want to consider the creation of a new `<@brjs-templates@>` tag, since this would allow us to embed the `<templates/>` or `<script type='text/templates'/>` tag directly into the page, removing the need for an additional round trip after the page has been loaded, and making it possible to use templates for even light pages like login pages.

This would unfortunately remove our ability to do browser detection though, since we now have to support static file export.

**Comment by dchambers** [comment]
I've created a [template spike repository](https://github.com/BladeRunnerJS/template-spike) to understand which of the desired use cases could be supported if we placed templates into `<template/>` tags within the page. I haven't been able to test IE8 yet because it turns out that [Chai](http://chaijs.com/) requires IE9, but all of the use cases originally defined work in IE9 except:

> Allow any tag to be used as the top-level node (e.g. &lt;td&gt;) and still work on IE8.

More progress on this to come tomorrow...

**Comment by dchambers** [comment]
I've now updated the [template spike repository](https://github.com/BladeRunnerJS/template-spike) so that it also works on IE8. This required the creation of an [`importNode()` polyfill for IE8](https://gist.github.com/dchambers/61b4088dc95e10076428) &mdash; none of the ones available on the web supported document fragments, which are needed when working with templates.

This is what I've learned from the spike:

  1. The Evergreen browsers can fully support a `<template/>` based solution.
  1. IE9+ can support all of the originally stated use cases, but would start downloading any images or videos embedded within templates in the background. &mdash; our templates tend not to have images since it's much more convenient to use CSS background images in BRJS.
  1. IE8 is so far unable to support `<template/>` tags that contain nested elements (e.g. `<td>`), and has some other well known quirks that developers are already used to (like uppercasing tag names in `innerHTML` output).

Before we proceed, we will need to check whether any of the other template solutions allow IE8 users to use embedded tags. If they don't, than this solution is as good as any other solution anyway.

**Comment by dchambers** [comment]
#671 (ability to support exotic elements) is also a use case we need to be able to cater to with any new solution.

**Comment by dchambers** [comment]
Some more information now that I've had a chance to investigate the IE8 failures:

  1. Using [HTML5Shiv](https://github.com/aFarkas/html5shiv) it's possible to get IE8 to parse and operate over arbitrary tags like `<template>`, but `childNodes` and `getElementsByTagName()` return spurious results for templates that contain tags like `<td>`, that would normally live within other tags &mdash; `innerHTML` returns correct results though.
  1. Although `innerHTML` can be used to get correct template contents in all cases, IE8 [doesn't allow innerHTML on `table` elements](http://stackoverflow.com/questions/1344470/why-is-document-getelementbyidtableid-innerhtml-not-working-in-ie8), so the textual template contents can't actually be made use of.
  1. The template shim we use in the spike creates a `DocumentFragment` object where the `childNodes` contains the actual nodes defined within the template, and provided this is created correctly, these nodes can successfully be added to the DOM even when they create tags like `<td>`.

Effectively, this means that the only way to process templates that contain tags like `<td>` in IE8 is to parse them using a JavaScript HTML parser!

Since document fragments are able to contain items like `<td>`, and since these can successfully be added to the main document, we could at some future point fix the final issues affecting IE8 using a JavaScript HTML parser, and this fix would be drop-in compatible. Therefore, I think we can have this as a known issue which we potentially fix later, assuming we still have users using IE8 by then.

Here's some example code showing that IE8 can handle document fragments that contain tags like `<td>`, and that it can subsequently add them to the main `document`:

```js
<body>
	<table>
		<tr id="tr"></tr>
	</table>
	<style>
		td {
			color: white;
			background-color: red;
		}
	</style>
	<script>
		var docFragment = document.createDocumentFragment();
		var td = document.createElement('td');

		td.appendChild(document.createTextNode('cell'));
		docFragment.appendChild(td);

		document.getElementById('tr').appendChild(docFragment);
	</script>
</body>
```

**Comment by dchambers** [comment]
Mandatory Changes:

  1. The BRJS server will be modified to allow templates to be provided within `<template/>` tags, and to wrap templates that aren't provided within `<template/>` tags, so that all templates provided to the client are wrapped within `<template/>` tags.
  1. In conjuction within the above change, the `HTMLResourceService` will be modified to return a fresh _document-fragment_ of the template contents, rather than providing a single template element (and re-using the same element each time at that).

Post 1.0 Changes:

  1. An optional `<@brjs-templates@>` tag will be made available that can be used to load the HTML templates within the page itself, rather than requiring a separate XHR request.
  1. The `HTMLResourceService` will be modified to detect if the templates have been pre-loaded, and use these directly instead of loading via XHR.
  1. IE8 support for nested `<td>` elements, etc, could be provided by using a JavaScript HTML parser to convert the `innerHTML` returned for each `<template/>` tag into a `DocumentFragment` instance.

**Comment by dchambers** [comment]
I ran into a problem late Friday that with the new design &mdash; that we no longer support multiple templates in a single template file unless those templates are wrapped in `<template/>` tags. I spoke to @janhancic, and this is apparently not very common (mostly used for sub-templates).

Since it would be difficult for us to handle this, and would negatively affect performance, I propose that we emit a warning when see a file containing multiple templates not using `<template/>` tags.

@andyberry88 / @james-shaw-turner are you happy with this?

**Comment by james-s-turner** [comment]
We ought to check all the Motifs and check how prevalent this is. It'a a shame to create another backward breaking change.

**Comment by janhancic** [comment]
I'll double check our app. Maybe @adamshone & @yasserf  can do the same for theirs.

**Comment by janhancic** [comment]
There's one file in our app that has multiple templates in the same file. We can easily split that (they really should be).

And there's also 4 files that have multiple templates in them. They are all in the libs. And they are all for workbench tools.

**Comment by dchambers** [comment]
@janhancic, not to worry, although this would be difficult for us to fix on the server, it's actually quite easy  to fix on the client, so I'll just move the processing there...

**Comment by dchambers** [comment]
Moving this to `ReadyForTest` even though the final optional change has not yet been done (this will be broken out into a separate issue):

  > IE8 support for nested <td> elements, etc, could be provided by using a JavaScript HTML parser to convert the innerHTML returned for each <template/> tag into a DocumentFragment instance.
