### ISSUE TITLE
Cannot import a blade from another apps default bladeset

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#1133]
To reproduce

Create App1 with a blade called 'bob; in a default bladeset

Create App2
Import 'bob' from App1

We first get an erro saying we cannot create a bladeset with the name "default" - we can change the bladeset name to something else which seemingly successfully imports the blade. When we try to use that blades workbench the ViewModel cannot be required. Looks like it has the incorrect require prefix

**Comment by ioanalianabalas** [comment]
Fixed by #1159.

**Comment by thecapdan** [comment]
Fixed
