### ISSUE TITLE
Add user templates documentation page on brjs-site

### ISSUE THREAD

**Issue by ioanalianabalas** [BladeRunnerJS/brjs#1136]
For the upcoming feature of user templates #126, we will also need to update the brjs site to include information about its use and configuration, e.g. how user templates may override sdk templates, where they are stored, what happens if templates do not exist, how empty folders are created if templates are missing for implicitly created entities.

**Comment by ioanalianabalas** [comment]
Please see https://github.com/BladeRunnerJS/brjs-site/pull/91.

**Comment by thecapdan** [comment]
This PR is merged.
