### ISSUE TITLE
in vanilla cygwin "brjs" script does not run

### ISSUE THREAD

**Issue by MstWntd** [BladeRunnerJS/brjs#1150]
Issue:

waqask@WAQASK-T430 /cygdrive/c/Users/waqask/Desktop/BladeRunnerJS/sdk
$ ./brjs start
Error: Could not find or load main class org.bladerunnerjs.runner.CommandRunner

The reason the script behaves like this is because Java under cygwin cant map "/cygwin/c/users/somedir" or "/c/users/somedir" to "C:\Users\somedir". 

When you run the "brjs.cmd" script, the cp provided has the actual "C:\", hence that will work.

sJira: http://yourls.caplin.com/7

**Comment by dchambers** [comment]
**Additional Information**:

@MstWntd has noticed that `brjs` can be used via GitBash, which happens not to prepend `/cygdrive` to the front of the drive letter. Although this can [be turned off in Cygwin](http://unix.stackexchange.com/questions/44677/how-do-i-get-rid-of-cygwins-cygdrive-prefix-in-all-paths), @MstWntd still suspects this won't work as he believes one of his clients is already set up in this way, but we should still confirm.

**Comment by ioanalianabalas** [comment]
Fixed by #1205.
