### ISSUE TITLE
NumericValidator does not consider floats or negative numbers as valid

### ISSUE THREAD

**Issue by avsmithy** [BladeRunnerJS/brjs#1152]
Floats and negative numbers should be considered valid according to `br/presenter/validator/NumericValidator`

```
m_oRegex = new RegExp(/^\d+$/);
m_oRegex.test(0.1) == false
m_oRegex.test(-1) == false
```

**Comment by dchambers** [comment]
@avsmithy, don't suppose you happen to have a pull-request for us? ;-)
