### ISSUE TITLE
release a new version of the appcache plugin

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1153]
Raising this in the BRJS repo so we don't forget out it.

The brjs-appcache plugin has been updated to use the new plugin APIs but a new jar hasn't been released (https://github.com/BladeRunnerJS/brjs-appcache/releases). Once we've moved all API classes to a separate package (#1085) and updated the plugin again we should build the jar and release a new version.

**Comment by andyberry88** [comment]
As part of this we should make sure the appcache plugin works with optional locales and the removal of the `base` tag @dchambers made (https://github.com/BladeRunnerJS/brjs/pull/1173). PR https://github.com/BladeRunnerJS/brjs-appcache/pull/1 fixes the issue in the previous codebase but may not be necessary now the relative paths have changed - the API should also be used for relative paths rather than calculating it manually.

**Comment by andyberry88** [comment]
There are 2 PRs for this issue. https://github.com/BladeRunnerJS/brjs/pull/1382 contains some minor changes to BRJS and https://github.com/BladeRunnerJS/brjs-appcache/pull/2 for the changes to the app cache plugin. Once both have been merged in we can release a new app cache version.

**Comment by thanhc** [comment]
Tested this change with the new appcache changes, enabled appcache loaded it in dev mode but with a version then killed brjs and then refresh browser and app is still loaded and the manifest is also created with correct version number, changed the version number and the manifest gets updated.
Also tested it when deployed onto tomcat by killing tomcat server and then refreshing page.

**Comment by andyberry88** [comment]
Although the 'dev' work has been finished on this we still need to actually release the manifest plugin artifact. Moving this back into `dev` until that's been done.

**Comment by andyberry88** [comment]
The AppCache plugin has been released - https://github.com/BladeRunnerJS/brjs-appcache/releases/tag/3.0.0
