### ISSUE TITLE
allows apps to live separately from the SDK

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1154]
Once BRJS can be run from the `PATH` (#1130), allow apps to live separately from the SDK so a single SDK can be used with multiple apps that exist in multiple locations.

**Comment by ioanalianabalas** [comment]
Please see #1231.

**Comment by andyberry88** [comment]
Pushing this back into `dev` as it looks like the `FileModificationWatcherThread` won't pick up changes in the `brjs-apps` directory when it doesn't live next to `sdk`.

```
public FileModificationWatcherThread(BRJS brjs, WatchKeyServiceFactory watchKeyServiceFactory) throws IOException
        {
                this.watchKeyServiceFactory = watchKeyServiceFactory;
                this.fileModificationRegistry = brjs.getFileModificationRegistry();
                directoryToWatch = brjs.dir().toPath();
                this.brjs = brjs;
        }
```

**Comment by ioanalianabalas** [comment]
Fixed by #1296.

**Comment by andyberry88** [comment]
A minor change following the sprint demo:

If I'm running a command inside of an app directory don't require `brjs-apps` to be present.  We need to look at how/if we do this.

Questions:
- What if the create-app command is run inside of an app directory with no `brjs-apps`?
- If serve is run do we just serve up a single app? (I imagine yes)
- Do we only support this if running commands directly inside of an app or anywhere inside the app?

**Comment by thanhc** [comment]
closing this ticket and instead opened #1331 for all remaining issues
