### ISSUE TITLE
Java Unit Tests Have Become Slower To Run

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1158]
When I run the Java unit tests on my machine three of them jump out as being particularly slow:

  * TemplateTests
  * CreateLibraryCommandTest
  * J2eeifyCommandPluginTest

It would be good to make these tests run quicker as we need to frequently run the unit tests while developing. @andyberry88 pointed out that all three of these tests share something in common &mdash; that they all use real templates &mdash; so this sounds like the first area to investigate.

**Comment by ioanalianabalas** [comment]
Fixed by #1157.

**Comment by thecapdan** [comment]
confirmed speed improvements in java tests
