### ISSUE TITLE
Creating blade via dashboard creates file with windows line endings (CRLF) on MacOSX 

### ISSUE THREAD

**Issue by james-shaw-turner** [BladeRunnerJS/brjs#1167]
To reproduce
Using BRJS version v0.14.3.0-gc36e03f select any app, and create a blade.
Go to command line and navigate to top of blade directory then:
"find . | xargs file"
You will see several files:
 ASCII text, with CRLF line terminators

**Comment by ioanalianabalas** [comment]
After a discussion with the team, we have decided that this is not something that we are going to fix. Most browsers on the popular operating systems handle both CRLF and LF properly, and this is the way BRJS has been working for some time without any problems.
