### ISSUE TITLE
The fixtures() function isn't compatible with CommonJS classes

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1178]
The `fixtures()` function currently allows you to specify a `FixtureFactory` class using dotted notation, where the class is available within the global namespace, for example:

```js
fixtures('pkg.MyFixtureFactory');
```

but doesn't allow you use _require-paths_, for cases where the class needs to be required, for example:

```js
fixtures('pkg/MyFixtureFactory');
```

If the class has neither dots nor slashes, then both approaches should be tried.

**Comment by ioanalianabalas** [comment]
Fixed by #1189.
