### ISSUE TITLE
Clean locale-service and br-locale-utility

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1186]
Clean up the unhealthy relationship between the _locale-service_ and `br-locale-utility`.

**Comment by dchambers** [comment]
We currently have a `LocaleService` interface that looks like this:

```js
LocaleService.setLocaleCookie = function(locale, days);
LocaleService.getLocale = function();
LocaleService.getPageLocale = function();
```

and for which the default implementaion is a thin wrapper around `br-locale-utility`. As it stands, this service has a number of faults:

  1. It assumes that all implementations will want to use cookies.
  2. It's `setActiveLocale()` method doesn't help with reloading the app at the correct URL (see #804).
  3. It isn't used by the _locale-forwarding_ page anyway, which just uses `br-locale-utility` directly.

Instead, I'd like to propose that we make available two distinct services that allow maximum flexibility in how locales are handled in BRJS. These would be:

  1. A _locale-provider_ service that allows the _active-locale_ to be provided or updated.
  2. A _locale-switcher_ service that causes the _active-locale_ to be used.

In this way, there could be alternative implementations offered for either or both parts. The service interfaces would like this:

```js
LocaleSwitcher.switch();
```

and:

```js
LocaleProvider.getActiveLocale();
LocaleProvider.setActiveLocale(locale);
```

**Comment by dchambers** [comment]
@andyberry88 are you happy with this?

**Comment by andyberry88** [comment]
@dchambers :+1: sounds good to me.

**Comment by dchambers** [comment]
I just noticed that `br/services/AppMetaService` also insists that there must be a thing called a _locale-cookie_.
