### ISSUE TITLE
Allow bundler to read a zip archive instead of parsing filesystem

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1203]
Suggested improvement is to be able to set the JS bundler to run against an archive file (be it zip/tar/other) containing the files to look for could be used instead.

http://yourls.caplin.com/d

**Comment by andyberry88** [comment]
I don't see any benefit in doing this. Since the bundlers use the model to discover assets and it expects a given structure we'd probably have to transparently unzip the archive anyway.

Given BRJS is a developer tool I can't really see the use case of wanting to run from an archive.

**Comment by andyberry88** [comment]
My comment on the internal support issue:

> At the core of BladeRunnerJS is a model which represents the structure of all apps, their libraries, the SDK and it's libraries. Each directory on disk corresponds to a node within the model and asset nodes can be discovered by plugins and added to the model. This allows us to have a centralised model which understands how to calculate the dependency tree and for developers to write their own plugins so more asset types are discovered and can define how dependencies are calculated from this new type of asset. For example the CommonJS dependency discovery is handled through a plugin which reads the file and discovers all 'require' statements. It also allows plugins to ask 'questions' about the structure of the app and assets' dependencies without having to understand anything about the dependencies itself - like the dependencies command plugin you've mentioned which is simply a 'graph' representation of the same dependency tree used to serve each bundle to the browser.

> The dependency process is done on demand, for example when a request is made to the server; tests are executed or the app is exported. Some plugins require multiple reads of a file, for like our 'NamespacedJS' plugin, and once the dependency tree is calculated the contents are read from disk and output to the browser or a file. We've taken this approach so we don't have to cache file contents, which would result in a large memory footprint, and have optimised our readers so they can be as performant as possible in returning content back to the browser or a file output stream. Running from a zip would result in multiple accesses, both to pull out the directory structure and also multiple reads of each file from the zip. This is likely to make it far less performant than unzipping the archive first.

This isn't something we're looking to implement so I'm going to close it as `wontfix`.
