### ISSUE TITLE
Bladeset templating not working

### ISSUE THREAD

**Issue by mayanks-caplin** [BladeRunnerJS/brjs#1208]
Create a new app
Create a new bladeset
When we try to open the new bladeset by selecting 'Run in Workbench' option - following error message is shown:

HTTP ERROR 500

Problem accessing /jkjkjkj/brjs/hjgjhg/workbench/en/. Reason:

    Error when trying to write the index page for apps/jkjkjkj/hjgjhg-bladeset/workbench/index.html; org.bladerunnerjs.model.exception.UnresolvableRequirePathException: Source file 'myBladeRequirePrefix/myBladeTitleViewModel' could not be found.

**Comment by ioanalianabalas** [comment]
Fixed by #1214.

**Comment by andyberry88** [comment]
@thanhc @mayanks-caplin @avsmithy  This is needed for the 0.15 release. Could you take a look at this today?

**Comment by thanhc** [comment]
this is now working
