### ISSUE TITLE
output timestamp in `--debug` logs

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1209]
I'm trying to debug a Caplin support issue relating to performance and the `--debug` logs don't provide any timestamp information so it's difficult to get an idea of any delays  in asset discovery etc. 
We should output the timestamp at the start of the log line if the `--debug` flag is used. Alternately if we don't want to clutter the developer console we could automatically write to a `debug.log` file that contains the timestamp when the debug flag is used. This would have the advantage of developers being able to see the console information as most have to pipe the output to a file.

**Comment by mayanks-caplin** [comment]
verified - timestamp is added to debug logs
