### ISSUE TITLE
[DISCUSSION] New BRJS feature confusion & feedback

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1211]
It's been suggested there may be some confusion about recent features or changes that have gone in to BRJS. Let's use this issue to collate any questions/concerns/feedback and we can add them all to a wiki page.

**Comment by janhancic** [comment]
- explain how services & aliases are supposed to be used in CommonJS modules (how to get them, how does BRJS "see" them)
- explain realms, how and where you should use them
- how do CommonJS & namespaced-js code work together, explain all the gotchas, etc
- testing in general, how to write UTs, how to write ATs. How to write tests that are mixed bag of both
- explain the new folder structure and how and where it can be used (src and tests)
- how does `src-test` work
- bladeset-less blades
- how to write proper JsDocs in terms of linking to other modules
- explain what a module is, exactly, and how it differs from a namespaced-js file

This is all stuff I struggled with or saw other people struggle with.

I'm probably going to add more stuff as I go along.

**Comment by stevesouth** [comment]
Is there a concept of a pipeline when writing a bundler plugin? I imagine we will need a jsx bundler soon, it would be nice to just write this part and have the ability to combine it with the current bundlers.

**Comment by andyberry88** [comment]
It's not obvious that resources can be in the 'src' directory and what the difference in behaviour is.

**Comment by andyberry88** [comment]
No one knows about 'parent' themes and how they work.

**Comment by janhancic** [comment]
Explain which classes were migrated from CT and explain that they shouldbe used instead of the ones in CT. One example is the `br/Errors` which was `caplin/core/Error` before.

**Comment by andyberry88** [comment]
Explain & document unbundled-resources at any level.

**Comment by andyberry88** [comment]
Add a "What does BRJS "see" in namespaced-js code?" or "Why isn't BRJS finding my namespaced-js dependency" page.

**Comment by andyberry88** [comment]
Requested by @bit-shifter: How do I add CSS to my tests running in JSTD?

**Comment by andyberry88** [comment]
How do I find out what the URL is for a bundle request? e.g. js bundles, css resource bundles etc.

**Comment by ccpetercc** [comment]
Some more features that could be added to be the docs:
 j2eeify command and the usage of JNDI Tokens
test-integration command
Referencing bundled resources in CSS - E.G.
	background-image: url('images/backgroundImage.png');

**Comment by andyberry88** [comment]
- should I check in `brjs.conf`
- when should the stats be tracked? (in CI or not?)
- how can I disable tracking for each command (`--no-stats` flag)
