### ISSUE TITLE
document new features

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1212]
we should document:
- [x] the usage stats plugin and how it works
- [x] running `brjs` from anywhere
- [x] BladeSet level workbenches

**Comment by ioanalianabalas** [comment]
Item 3 is fixed by https://github.com/BladeRunnerJS/brjs-site/pull/103.

**Comment by ioanalianabalas** [comment]
Item 2 is fixed by https://github.com/BladeRunnerJS/brjs-site/pull/104.

**Comment by ioanalianabalas** [comment]
Item 1 is fixed by https://github.com/BladeRunnerJS/brjs-site/pull/105.

**Comment by andyberry88** [comment]
The PR for this has already been reviewed and merged.
