### ISSUE TITLE
Missing open bracket on website code snippet http://bladerunnerjs.org/docs/use/getting_started/

### ISSUE THREAD

**Issue by priteshg** [BladeRunnerJS/brjs#1215]
Update the Todo Input Blade
Back in our input blade we can access the EventHub service using the via ServiceRegistry using the require( 'service!<service name>' ) syntax, as shown in the InputViewModel constructor below:

'use strict';

var ko = require( 'ko' );

var ENTER_KEY_CODE = 13;

function InputViewModel() {
    this.todoText = ko.observable( '' );

    this._eventHub = require 'service!br.event-hub' ); <-----------------open bracket needed
}

InputViewModel.prototype.keyPressed = function( item, event ) {
    if( event.keyCode === ENTER_KEY_CODE ) {
        var todoTextValue = this.todoText();
        console.log( todoTextValue );
    }

    return true;
};

module.exports = InputViewModel;

**Comment by ioanalianabalas** [comment]
Fixed by https://github.com/BladeRunnerJS/brjs-site/pull/95.
