### ISSUE TITLE
Ensure Docs Are In-Line With API and ensure JavaDocs are complete

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1220]
For the 1.0 release, we need to ensure that all of our documentation and all of the screenshots are still correct based on all the changes we've made to get to 1.0. For example, I've noticed that most of the screenshots we have are now out of date now that locales no longer appear within the URL at all (for single-locale apps), or are files now instead of directories (for multi-locale apps).

**Comment by andyberry88** [comment]
As part of this issue we should also make sure the JavaDocs are up to date and all our interfaces are doc'd. Also, the API docs for 0.15.2, 0.v15.3 and 0.v15.4 haven't been uploaded so that should be done in addition to the 1.0-RC1 and 1.0 API docs.

**Comment by ioanalianabalas** [comment]
Fixed by https://github.com/BladeRunnerJS/brjs-site/pull/106.

**Comment by james-s-turner** [comment]
In the internationalisation site page  the section ### Multi-Locale Apps is confusing. It's not obvious what pages the developer has to create and what is "automagically generated". Maybe a simple flow diagram would be useful to explain the process.

**Comment by ioanalianabalas** [comment]
Javadocs have been added in https://github.com/BladeRunnerJS/brjs/pull/1377.

I have spoken to @james-s-turner about not being able to find the Multi-Locale Apps section and he will get back to me.
