### ISSUE TITLE
[feature] BRJS should throw an exception if requiring something you shouldn't

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1232]
If my blade is requiring something from the `default-aspect`, then that works just fine when running the app. But when I then test my blade, I get an exception saying that it can't resolve the desired require path (which is, I guess, wrong on it's own, it should distinguish when something isn't there and when something isn't allowed to be required).

I would like to get an exception no matter how and where I'm running my code.

**Comment by ioanalianabalas** [comment]
Fixed by #1291.

**Comment by andyberry88** [comment]
#1291 doesn't go the whole way to fixing the issue that @janhancic was meaning. We should also throw an exception is a Blade class depends on another Blade while bundling for an Aspect. This is probably the reason we had a similar `scopeAssetContainers` method on `AssetContainer` that @dchambers added and I removed without breaking any tests months ago. It sounds like we should add that back in and check that the dependency is within the asset container scope.

**Comment by dchambers** [comment]
> #1291 doesn't go the whole way to fixing the issue that @janhancic was meaning.

Okay, but this does help this issue, and definitely does fix #565 (so I've commented as fixed).

**Comment by andyberry88** [comment]
#1318 is now the PR for this. I've taken most of the changes from #1291. applied them on top of develop and then built on top of it for the extra scope enforcement.

**Comment by ccpetercc** [comment]
2 issues:

- For warning messages when no-strict-checking is used do not alert the user of require statements breaking the blade/bladeset dependency architecture

e.g.
```
warning message: Strict checking has been disabled for the directory 'brjs-apps/brjstodo/blades/items/src' and therefore the Asset 'blades/items/src/ItemsViewModel.js'. This allows the Blade class to directly depend on another Blade class when the App loaded. This dependency should be broken using Services and the file 'brjs-apps/brjstodo/blades/items/src/no-strict-checking' should be removed to re-enable the scope enforcement.
```
Does not include require statements breaking the rules

- Duplicate no-strict-checking warning messages are output by brjs

**Comment by andyberry88** [comment]
@ccpetercc can you merge in https://github.com/BladeRunnerJS/brjs/pull/1318 before I look at the above? We're getting to the state where so much relies on other PRs that it's going to be easier to merge everything in a take another branch from `develop`.

**Comment by andyberry88** [comment]
The issues above are fixed in #1340.

**Comment by thanhc** [comment]
@andyberry88 we now displaying the warning message:
The class 'thanh/items/ItemsViewModel' depends on the class 'thanh/input/InputViewModel' which is outside of it's scope - this dependency should be broken using Services.

however the no-strict-checking warning message is still be outputted multiple times

**Comment by andyberry88** [comment]
Had a chat with @thanhc. It looks like the message is printed multiple times possibly because there are multiple blades and several bundlesets may have been generated. Given people shouldn't be using this flag (and we're happy it being annoying if they do) this isn't something that's worth the time to look into further.
