### ISSUE TITLE
[feature] Multiple themes in the app

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1234]
As part of customer customization of our app, we need to create new CSS files. I would like to be able to have those files in a separate theme, and configure the customer app to use our base theme and their customer theme.

**Comment by andyberry88** [comment]
@janhancic Is this not possible via https://github.com/BladeRunnerJS/brjs/issues/401? If you name a theme with the format `<parentThemeName>-<variantName>` the bundler will automatically pull in all parent CSS files if the child theme is requested.
e.g. given the themes `red` and `red-dark` if `red-dark` is used all assets from `red` is pulled in followed by `red-dark`.

**Comment by janhancic** [comment]
I wasn't aware of that. And apparently neither was @dchambers :)

I'll give it a spin.

**Comment by dchambers** [comment]
Wow, what a pleasant surprise! Not sure how I missed this happening?

**Comment by andyberry88** [comment]
I'm sensing a theme here - we have a distinct lack of docs around some features. Will add it to https://github.com/BladeRunnerJS/brjs/issues/1211 to discuss/write docs for.
