### ISSUE TITLE
Validation interfaces should not be housed within presenter.

### ISSUE THREAD

**Issue by bit-shifter** [BladeRunnerJS/brjs#1241]
We would like to write validators in a non-presenter library but find that we need to reference presenter housed validator interfaces.

It seems that the interfaces and a number of the validator implementations are not presenter specific.

With that in mind, I propose that the following classes and interfaces are moved to a more generic location, perhaps `br/validation`:

interfaces:
`br/presenter/validator/ValidationResult.js`
`br/presenter/validator/Validator.js`
`br/presenter/validator/ValidationResultListener.js`

validator implementations:
`br/presenter/validator/NumericValidator`
`br/presenter/validator/ISODateValidator`
`br/presenter/validator/NotEmptyValidator`
`br/presenter/validator/EmailValidator`

any i18n keys also need to re-homed to the new library.

**Comment by bit-shifter** [comment]
The CrossPropertyValidator interface could also be moved as it doesn't appear to have any presenter dependencies:

`br/presenter/validator/CrossPropertyValidator`

**Comment by janhancic** [comment]
:+1:

**Comment by dchambers** [comment]
@bit-shifter, I've taken a look at this and I've come up with almost the same list of candidate modules as you:

Validator Interfaces:

  * `ValidationResult`
  * `ValidationResultListener`
  * `Validator`

Validator Classes:

  * `EmailValidator`
  * `ISODateValidator` (but this currently relies on `ct.presenter.validator.invalidISODateFormat` and `ct.presenter.validator.valueNullUndefinedOrEmptyString` i18n tokens!?)
  * `NotEmptyValidator`
  * `NumericValidator`

except that I think the `CrossPropertyValidator` interface is `presenter` specific as the properties it refers to are `presenter` properties.

Additionally, I think all of the formatting modules within `br/presenter/formatter` should be moved to `br/formatting`.
