### ISSUE TITLE
BRJS doesn't renamespace Blades in the 'default' BladeSet

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1245]
We have a bladeset-less blade which mainly consists of grid XML files and one JS file. The blade is a ComonJS blade.

When you export our app and import it nothing in that blade get's re-namespaced. That includes i18n tokes, grid XML files and JS files.

**Comment by janhancic** [comment]
Tagging @sospirited as he found the issue.

**Comment by andyberry88** [comment]
This is fixed by https://github.com/BladeRunnerJS/brjs/pull/1261

**Comment by thanhc** [comment]
Oddly, not able to reproduce the issue with i18n and js files not being namespaced correctly when in the default bladeset only xml causing an issue.  But re-tested the issue using the offending app and everything has been namespaced correctly.
