### ISSUE TITLE
Re-instate the formatter UTs

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1247]
Somewhere along the line, the unit tests for the formatters we provide went missing (I only noticed while doing #1246). These may have originally made it into git, or may be in the final `last-stand` branch within perforce. Find them and resurrect them.

**Comment by thecapdan** [comment]
I was up all night looking, but I finally found them down the side of the sofa:

https://github.com/BladeRunnerJS/brjs/tree/master/brjs-sdk/sdk/libs/javascript/presenter-formatter-tests_NODIST/tests/test-unit/js-test-driver

They are still being run. We had to move them when they were being naughty: they were intermittently failing in IE when they ran alongside the other presenter tests. We did timebox an investigation at the time but the QA made a judgement call that it was best to separate them. 

Might be worth re-investigating at a time when we have an oubliage of QAs on the team...

**Comment by dchambers** [comment]
@thecapdan, I have to know. What is an 'oubilage'? Oh, and thanks for finding the lost tests!

**Comment by thecapdan** [comment]
@dchambers it means whatever you want it to mean:) It is an incredibly capricious word that is able to adapt to it's surroundings. In the case above, it means a 'wide and colourful assortment'

**Comment by dchambers** [comment]
LOL ... that's made my day :+1: I couldn't help but ask since it's the second time you've used it in as many days.
