### ISSUE TITLE
update site docs for 1.0 release

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1271]
Update all brjs site docs, here are a few things to update for sure:
- update all code snippets to remove the <@base.tag@> 
- mention about <@unbundled-resources@/> tag.

**Comment by ioanalianabalas** [comment]
Fixed by https://github.com/BladeRunnerJS/brjs-site/pull/102.

**Comment by andyberry88** [comment]
The PR for this has already been reviewed and merged.
