### ISSUE TITLE
McAffee virus scanner makes the app take 20+ mins to load

### ISSUE THREAD

**Issue by willalbone** [BladeRunnerJS/brjs#1283]
In the process of upgrading to CT4 / Motif 2.1.1. When running ./brjs serve and navigating to localhost:7070/dashboard it never loads. After around 25mins the browser will redirect to localhost:7070/dashboard/en but the dashboard still does not load. Navigating directly to /dashboard/en also has the some result. CPU profile screenshot from VisualVM is attached below. Task manager shows that the java process is using around 25% CPU for the whole time ./brjs serve is running and is the only process using a significant amount of CPU. Running ./brjs serve --debug shows that brjs looks to be constantly trying to resolve dependencies. 

BRJS version: 0.14.3.0
CT version: 4.0.3
Java version: 1.8.0_40 64bit
JAVA_OPTS: -Xms1024m -Xmx4096m
OS: Windows 7 Enterprise 64bit

![cpu profile](https://cloud.githubusercontent.com/assets/2067076/6691540/1f3ef6d4-ccbf-11e4-88b5-b5cce78fb805.png)

I have also tried downloading the latest version of BRJS from the website (0.15.1.0) and have the same issue though it has a different CPU profile:

![cpu profile 15](https://cloud.githubusercontent.com/assets/2067076/6692076/5dea7874-ccc2-11e4-98be-b28f8ef25487.png)

**Comment by andyberry88** [comment]
Hi @willalbone we've seen a few issues similar to this recently. Do you have any kind of virus scanner that could be slowing down the dependency calculation process? Are you able to try loading it on another machine to see if the same happens?

**Comment by willalbone** [comment]
All the Santander boxes have McAffee virus scanner installed but we aren't able to disable it or make any change to the settings. They are also all VMs. Running it on another of the Santander machines results in the same outcome but I have had no problems running it on my laptop using either Windows 7 or Ubuntu.

**Comment by andyberry88** [comment]
It sounds like it could well be the McAffee virus scanner, probably the on access scanner. Are you able to get an exclude added for the BladeRunnerJS and apps directory so it no longer performs on access scanning for those files?

**Comment by andyberry88** [comment]
Failing being able to add an exclude we'll need to try and work out exactly what is causing the slow down. I'll try giving you a version without our file watcher thread running and see if that's the culprit and we'll go from there.

**Comment by andyberry88** [comment]
It looks like the fix for this is to use the [Apache Commons File watching packages](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/monitor/package-summary.html) instead of the Java7 file watcher. Since we have to watch every directory individually with the Apache Commons approach it could be less performant for large codebases so we'll make this configurable via `brjs.conf`.

**Comment by andyberry88** [comment]
This is fixed by #1306 which will be in the v0.15.3 release.
