### ISSUE TITLE
Not all images are being exported when creating a war

### ISSUE THREAD

**Issue by jngo00** [BladeRunnerJS/brjs#1288]
I have four images inside my default aspect folder, under themes ---> svg ---> 4 svg image files.
When exporting a war and inspecting the war that was generated it would seem that we are missing 2 of the 4 svgs.

**Comment by andyberry88** [comment]
@jngo00 Are these images used anywhere in your app? We've started filtering the set of output files to only contain those that are actually used within the app (https://github.com/BladeRunnerJS/brjs/issues/745).

**Comment by jngo00** [comment]
Yep these images are being used in the app

**Comment by andyberry88** [comment]
How are they being used? Is it via the CSS or the index.html? Are they all being used in the same way?

**Comment by jngo00** [comment]
used in css, and yep they are all being used in the same way

**Comment by jsorbello** [comment]
Turns out these images weren't directly referenced in css. The names were being constructed via string concatenation with variables eg: var fullName = "some/base/path/" + fileName;

**Comment by ioanalianabalas** [comment]
Spoke to @jngo00 and given that they determined the reason why the exported images were not present, he recommended I close the issue.
