### ISSUE TITLE
test-integration location doesnt work with default aspect

### ISSUE THREAD

**Issue by ccpetercc** [BladeRunnerJS/brjs#1297]
Integration tests must currently be located within an *-aspect or workbench folder. This constraint should not be applied to the test-integration folder since new BRJS applications do not require a default-aspect folder (they do not have one by default)

See: org.bladerunnerjs.legacy.command.testIntegration.IntegrationTestFinder.isValidTestDir

**Comment by ioanalianabalas** [comment]
Fixed by #1330.
