### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by ccpetercc** [BladeRunnerJS/brjs#1299]
The page:
http://bladerunnerjs.org/docs/reference/available_services/
has lots broken links
For example: http://apidocs.bladerunnerjs.org/latest/js/XmlResourceService.html

This should be: http://apidocs.bladerunnerjs.org/latest/js/module-br_services_XmlResourceService.html

**Comment by ioanalianabalas** [comment]
Fixed by https://github.com/BladeRunnerJS/brjs-site/pull/100.
