### ISSUE TITLE
MapUtility#deepClone doesn't clone arrays

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1301]
The `MapUtility#deepClone` function doesn't properly clone a map that has an array in it. The array gets converted into an object.

The funny thing is that the docs for `deepClone` actually say: 

> (note that non-map objects are not handled correctly)

Which probably means we can't just fix this without potentially breaking backwards compatibility as some people might be relying on the current behaviour.

@james-shaw-turner what do you think? Is it low risk enough that we can just fix it or not?

**Comment by james-s-turner** [comment]
I'd say spike it by patching in the Motifs and if it doesn't break much then go for it.

**Comment by janhancic** [comment]
Sounds like a plan. I'll try to find some time and test it out.

**Comment by ccpetercc** [comment]
Fixed in: #deep_clone_fix
