### ISSUE TITLE
Ability to exclude tests from application libs when exporting an application

### ISSUE THREAD

**Issue by sospirited** [BladeRunnerJS/brjs#1320]
We have a use case where we care about only exporting tests in an application specific to the application code itself (aspects, bladesets, blades) and not the libs which it depends on.

For us to do this at the moment, it requires build work where we would have to:
1) Take a side-ways copy of our application and the sdk to a temp location 
2) Run custom build steps to strip out tests from the libs that our application has
3) Run the export-app command on the app in this modified side-ways copy we have in the temp location

I was wondering if BRJS could provide this as an optional flag option that could be passed in.

E.g. something like:
`brjs export-app <app-name> -xlibtests`

**Comment by andyberry88** [comment]
@sospirited Since this is a custom feature that not all BRJS users will want to do it's not something we're likely to add to the core BRJS codebase. You could right a custom command that uses the existing `build-app` command and filters the neccessary files, or continue with the custom build step.
