### ISSUE TITLE
Getting brjs emails from jenkins

### ISSUE THREAD

**Issue by lukeapage** [BladeRunnerJS/brjs#1341]
Hi,

I'm no longer involved in the project using brjs. I've just started getting emails..

```
BUILD FAILURE
Build URL	http://jenkins.caplin.com/job/BRJS-develop/29/
Project:	BRJS-develop
Date of build:	Wed, 15 Apr 2015 10:05:08 +0100
Build duration:	29 min
Built on machine:	jenkins-cent5-004.caplin.com
Build Cause:	[Started by an SCM change]
```

Please can I be unsubscribed?

**Comment by andyberry88** [comment]
Hi @lukeapage, 
Sorry for the spam! We've update the Jenkins config so it only emails the core BRJS team. You shouldn't see these any more, please give me a shout if you start seeing them again.
