### ISSUE TITLE
Enforce "strict mode" at application level

### ISSUE THREAD

**Issue by trueadm** [BladeRunnerJS/brjs#1347]
I believe that in today's age of JavaScript development, strict mode should be something that should be enforceable at an app level (excluding libraries) to help developers avoid mistakes and write better code. Is this something that the people would regard as useful if implemented?

In terms of implementation, it could either:

- add "use strict" to the top of application JS files that are missing it by default
- suggest "use strict" to the user as a form of warning on files missing it

Third-party implementations of this on similar bundling tools include:

https://www.npmjs.com/package/strictify (Browserify)
https://www.npmjs.com/package/strict-loader (Webpack)

**Comment by janhancic** [comment]
Enforcing this would be a bad thing to do. A lot of apps would break. An optional enforcement seems like a better idea. And add warnings.

**Comment by trueadm** [comment]
I meant as an option to enforce. :) It does worry me that apps would break though?! Is that in regards to legacy projects or recent projects?

**Comment by janhancic** [comment]
All projects that are using code written years and years ago. New stuff is being written with `use strict`.

**Comment by andyberry88** [comment]
This is probably not something that we want to add in to BRJS core as it could different from app to app. Theres an issue to add JSHint support (#101) which would probably cover this anyway
