### ISSUE TITLE
it-app throwing error in IE

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1355]
When opening the IT-app in IE we're getting the following error:

	return require('service!br.xml-service').getXmlDocument("bundledXml")[0].children[0].innerHTML;
};
Unable to get property '0' of undefined or null reference - with the children being undefined.

This seems to have never worked in IE from what I can see.

**Comment by andyberry88** [comment]
Fixed in 128e57a4463a17a9ea86b812a56453af8e63b287.
