### ISSUE TITLE
IE8 error's when using html.bundle tag

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1380]
In CT if we use the html.bundle tag in the index.html then the app loads with error's in IE8

**Comment by andyberry88** [comment]
The app wasn't loading because `document.body` was null in one of the knockout plugins in the app/lib code. Moving all the JS in `index.html` in to the `body` rather than `head` fixes the problem. This looks like it's an app bug rather than in BRJS.
