### ISSUE TITLE
support favicon.ico in apps

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1381]
`favicon.ico` in the root of apps isn't served or part of built apps at the moment. Create a content plugin to serve `favicion.ico` files in the root of the app folder.

**Comment by ioanalianabalas** [comment]
Fixed by #1430.

**Comment by thecapdan** [comment]
@ioanalianabalas is the favicon.ico meant to be in the dashboard apps root folder, or should it be in default-aspect? also, the link to the favicon.ico in the dashboards index.html is incorrect, it points to unbundled resources
