### ISSUE TITLE
Remove all references to the old Component interface

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1383]
Apart from a single backwards compatibility test, there should be no reference to the old `Component` interface, or reliance on any of its methods, like `getElement()`.

As a starter, the following areas will need to change:

  * The [Getting Started](http://bladerunnerjs.org/docs/use/getting_started/) guide and [TODO MVC](https://github.com/BladeRunnerJS/brjs-todomvc-knockout) branch will need to be updated so they use a `SimpleFrame` and trigger the `attach` event, instead of only using the deprecated `getElement()` method.
  * The dashboard should be updated so that it no longer uses the old `Component` interface (started in #1379).
  * The `Workbench.displayComponent()` method should trigger `attach` (already done as part of #1379).
  * Any library code that relies on the old `Component` should be updated too.

This [comment](https://github.com/BladeRunnerJS/brjs/issues/1374#issuecomment-101186054) may contain more relevant information.

**Comment by ioanalianabalas** [comment]
- updates to the Getting Started guide: https://github.com/BladeRunnerJS/brjs-site/pull/108
- updates to the `brjs-todomvc-knockout` have been pushed to the project's `master

**Comment by andyberry88** [comment]
#1390 looks good. I'd like to discuss https://github.com/BladeRunnerJS/brjs-site/pull/108 though. IMO that makes the getting started guide much more complex so we should either simplify the interfaces use or not use it at all in the getting started guide (see my comment on the `brjs-site` PR - https://github.com/BladeRunnerJS/brjs-site/pull/108#issuecomment-105929497).

**Comment by andyberry88** [comment]
@dchambers changes have been made in the existing PR (https://github.com/BladeRunnerJS/brjs-site/pull/108).

**Comment by thanhc** [comment]
#1390 is causing workbenches to not load, see PR for more detials
