### ISSUE TITLE
FXMotif first load taking a long time

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1400]
While trying to upgrade the FX Motif to use BRJS 1.0, the initial load of the Motif is taking a very long time 40+ seconds it even causes chrome to stop working and pop up the kill chrome now window, looking at the network tab it seems to take a long time to get an image 40 seconds, once this image is returned then the rest of the app loads fine.

The image path is http://localhost:7070/fxtrader/v/dev/cssresource/aspect_default/theme_cotton/images/logo_with_bg.png

There is a branch in the motif which has been upgraded to 1.0 called brjs1.0Upgrade

**Comment by janhancic** [comment]
Not as bad, but I've experienced longer load times with our app too.

**Comment by andyberry88** [comment]
@janhancic files created inside of the `generated` folder were invalidating the `bundleSet` cache, causing a new dependency analysis to happen during one of the requests as the app loads. The delay was then dependent on the speed of the machine and the number of assets in the dependency graph.

**Comment by thanhc** [comment]
This has made some difference to the first load time, its no longer waiting ages for the image but the overall load time is still slower than 0.15.4, on first load it use to take about 15 secs, with RC 1.0 ~30secs, and on refresh ~3 compared to ~5 seconds on 1.0, closing this issue as there's another one to look at general performance.
