### ISSUE TITLE
Remove 'caplin' and 'caplinx' from reserved namespaces

### ISSUE THREAD

**Issue by ioanalianabalas** [BladeRunnerJS/brjs#1404]
We need to remove the reserved namespaces from `org.bladerunnerjs.utility.NameValidator` and the dashboard so that Caplin users of BRJS can create apps with those namespaces. Originally raised by @hobojed.

**Comment by ioanalianabalas** [comment]
@andyberry88, can you reference the pull request where this was completed? Thank you. :)

**Comment by andyberry88** [comment]
@ioanalianabalas This is your pull request. Not sure why it's needed.

**Comment by andyberry88** [comment]
@ioanalianabalas As far as I know this hasn't bene completed, it's your issue that was raised yesterday. Is it something that's needed/has been completed?

**Comment by ioanalianabalas** [comment]
@andyberry88, that is what I know as well, but I can see you marked it as 'Ready for Dev Review'?

**Comment by ioanalianabalas** [comment]
Fixed by #1424.
