### ISSUE TITLE
Allow hiding warnings from BRJS

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1409]
Using BRJS RC1

When I run tests for one specific lib (`brjs test ../apps/myapp/libs/foo-lib`) I get this warning:

```
The file 'D:/solutions/st/apps/myapp/libs/foo-lib/tests/test-unit/js-test-driver/resources/aliases.xml' is using the deprecated xmlns attribute and should be updated to use http://schema.bladerunnerjs.org/aliases.
```

Which is OK, but I also get it for all other libs (including ones in the SDK!) that have this problem.

I expect to only see the warning for the location I'm running the tests for.

**Comment by andyberry88** [comment]
I'm not sure we can, or IMO should spend time trying to, only display the warning for the current tests. Its a warning generated by the model code when it's calculating dependencies for all the code you have available. 

We should fix the warning for any SDK libs for 1.0 though since they aren't something that are under your control as a BRJS user.

**Comment by janhancic** [comment]
It's really annoying seeing 20+ lines of warnings before I get to see the results of my tests. But I can see your point of view too, as "all" it would take to fix this is for us to update the URLs.

Is there a flag I can pass to BRJS so it swallows this sort of warnings?

**Comment by andyberry88** [comment]
> Is there a flag I can pass to BRJS so it swallows this sort of warnings? 

Not at the moment. We should perhaps add a `quiet` flag which would suppress warning level logs.

**Comment by ioanalianabalas** [comment]
Fixed by #1433.

**Comment by thecapdan** [comment]
this was merged by accident - this does not work as expected. '--quiet' flag removes all logging. needs another look

**Comment by andyberry88** [comment]
` this does not work as expected`:

It might not work as expected but it is doing exactly as the code says to do :smile:  JSTD logs at warn level and the `--quiet` flag causes only errors to be displayed - so it's doing exactly as asked. We have a `logger.console()` method which always logs to stdout so I've added a `LogLevel.console` enum which corresponds with this and JSTD now logs here.

**Comment by thecapdan** [comment]
@andyberry88 

here's the output now when using the --quiet flag:

```
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (4.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (4.00 ms)
.
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (1.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (1.00 ms)
.
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (1.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (1.00 ms)
.
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (1.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (1.00 ms)
.
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (1.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (1.00 ms)
.
Total 1 tests (Passed: 1; Fails: 0; Errors: 0) (2.00 ms)
  PhantomJS  : Run 1 tests (Passed: 1; Fails: 0; Errors 0) (2.00 ms)
```

**Comment by andyberry88** [comment]
Thats the output I'd expect. Because we're forking the JSTD process and it uses it's own logging mechanism it's never going to be perfect. Generally if you use a `--quiet` in most CLI commands you only get an output if something goes wrong. While this doesn't strictly follow that it's better than it was and probably as near as we'll get until we replace the legacy test commands.

**Comment by thecapdan** [comment]
ok. at least it doesn't swallow the failure messages when tests fail, so I it adds some value i suppose...

![tumblr_muwangqmd51syeot2o1_500](https://cloud.githubusercontent.com/assets/6085260/8502203/dfb893b8-21a4-11e5-84b7-b44dd9799a86.gif)
