### ISSUE TITLE
Changes made to jsunitextensions/Clock are not mentioned anywhere

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1410]
After upgrading to RC1 I got some tests failing with a new error message. After some digging I found it in the `Clock.js` file. After following the error message's instructions I was able to get my tests passing again. But I didn't find this mentioned in the release notes as a backwards braking change.

**Comment by andyberry88** [comment]
Thanks @janhancic, something that definitely should have been in the release notes. I'll add this to the 1.0 milestone.

**Comment by andyberry88** [comment]
Closing this as duplicate since it's covered in #1411.
