### ISSUE TITLE
Time to run the tests has increased

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#1413]
When I upgraded to RC1 I got a feeling tests are taking longer to run. So I did some measuring.

I timed one lib that has 223 UTs and 22 ATs. I tested against `RC1` and `0.15.4.0-gbd82eac`. With both versions I ran the tests 4 times and got this results:

`RC1`:
```
min time:
real    0m29.384s
user    0m0.180s
sys     0m0.476s

max time:
real    0m33.414s
user    0m0.288s
sys     0m0.397s
```

`v0.15.4.0-gbd82eac`:
```
min
real    0m27.100s
user    0m0.365s
sys     0m0.367s

max
real    0m27.305s
user    0m0.319s
sys     0m0.475s
```

The command I ran was: `time brjs test ../apps/myapp/libs/mylib`.

And as always this is on Windows 7 with Java `1.7.0_55`.

**Comment by dchambers** [comment]
@janhancic, this actually isn't a huge slow down, but I'm fully aware that it was already much slower than we'd like already, so we should definitely investigate and see if we can do anything to improve this.

**Comment by janhancic** [comment]
This is just one library! We have about ~40 "things" that have tests (some just UTs, some just ATs and some both). Add a 3 seconds to each "thing" and it adds up to 2 extra minutes to run the tests. I'd say that's pretty huge :)

**Comment by andyberry88** [comment]
It sounds like this should be something thats looked at with reasonably high priority after the 1.0 release. We should probably do another performance review to see if anything can be shaved off of the bundle generation time.
