### ISSUE TITLE
[EMITR]  Emitr shouldn't silently swallow errors in user code

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1422]
Raising this here so it doesn't get lost since Emitr is a seperate repo.

- [x] Emitr shouldn't silently swallow errors in user code - https://github.com/BladeRunnerJS/emitr/issues/10

**Comment by ioanalianabalas** [comment]
Fixed by https://github.com/BladeRunnerJS/emitr/pull/11.

**Comment by andyberry88** [comment]
@ioanalianabalas The `Emitr` subtree inside of the `brjs` repo needs updating so it can pull in the changes you've made to the `Emitr` library.

**Comment by ioanalianabalas** [comment]
@andyberry88 this is now done in #1445.
