### ISSUE TITLE
Fix website 404s

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1425]
We've got several 404s on the website, they should all be fixed.

Broken link|Linking from
------------ | -------------
http://bladerunnerjs.org/docs/faq/|http://bladerunnerjs.org/
http://bladerunnerjs.org/docs/concetps/services/|http://bladerunnerjs.org/blog/using-angularjs-with-bladerunnerjs
http://bladerunnerjs.org/docs/concetps/libraries/|http://bladerunnerjs.org/blog/using-angularjs-with-bladerunnerjs/
http://bladerunnerjs.org/docs/concepts/apps/|http://bladerunnerjs.org/docs/concepts/model/
http://bladerunnerjs.org/docs/concepts/interaces|http://bladerunnerjs.org/docs/concepts/classes/
http://bladerunnerjs.org/docs/use/create-bladeset|http://bladerunnerjs.org/docs/use/internationalization/
http://bladerunnerjs.org/docs/use/create-blade/|http://bladerunnerjs.org/docs/use/internationalization/
http://bladerunnerjs.org/docs/concepts/bundling/|http://bladerunnerjs.org/docs/concepts/assets/
http://bladerunnerjs.org/docs/concepts/bundler/|http://bladerunnerjs.org/docs/concepts/modules/
http://bladerunnerjs.org/blog/oss-events-success/www.spaconference.org/spa2014/|http://bladerunnerjs.org/blog/oss-events-success/
http://bladerunnerjs.org/docs/use/install/war-files|http://bladerunnerjs.org/docs/use/install/
http://bladerunnerjs.org/docs/concetps/service_registry/|http://bladerunnerjs.org/blog/using-angularjs-with-bladerunnerjs/
http://bladerunnerjs.org/docs/use/create-app|http://bladerunnerjs.org/docs/use/internationalization/
http://apidocs.bladerunnerjs.org/dashboard|`<this is linked from all js doc pages from previous releases - should probably be fixed by a placeholder page that just explains what the dashboard is and where its hosted by default >`
http://bladerunnerjs.org/docs/concepts/presenter/|http://bladerunnerjs.org/blog/productivity-why-ghost-chose-emberjs/

**Comment by andyberry88** [comment]
Fixed by https://github.com/BladeRunnerJS/brjs-site/pull/112

**Comment by ioanalianabalas** [comment]
Dev-reviewed :+1:
