### ISSUE TITLE
Bundle file writing improvements

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1426]
We recently identified a number of opportunistic improvements that should be easy to make, and which it would be good to get into the hands of users early in case they fix the test reliability problems people are seeing. These are issues 11, 12 & 14 from [this comment](https://github.com/BladeRunnerJS/brjs/issues/1370#issuecomment-111986192).

**Comment by andyberry88** [comment]
Fixed by #1427.
