### ISSUE TITLE
Create a Keybinding service

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1428]
@janhancic has identified the need for a service that allows blades to register actions that users might want to run using a key-combination. For example:

```js
var keybindingService = require('service!br.keybinding-service');
keybindingService.registerAction('acme.explode-tnt', "Causes all TNT to be exploded.",
    tnt.explode.bind(tnt)).withDefaultBinding('Ctrl-Shift-E');
```

Apps are free to override the default key-binding suggested by a blade (assuming a default has been provided), like so:

```js
keybindingService.rebindAction('acme.explode-tnt', 'Ctrl-E');
```

Blades can ensure that their actions have unique identifiers by prefixing any action ids with the blade's namespace. If multiple blades attempt to set the same default key-binding then none of the actions inherit the default, and the app is required to explicitly bind these actions.

**Comment by dchambers** [comment]
Although I've created this issue now, it won't be assigned a milestone since we're not planning to implement ourselves, and will instead wait for @janhancic to donate us an implementation instead; thanks @janhancic :+1:.

**Comment by janhancic** [comment]
> If multiple blades attempt to set the same default key-binding then none of the actions inherit the default, and the app is required to explicitly bind these actions.

An action with an existing binding can be added anytime in the app's life. Would that mean that a binding that worked now stopped working, because another action was added with the same default binding? That doesn't sound right.

**Comment by janhancic** [comment]
After talking with @dchambers we decided that a blade would not provide the keybinding, it would be up tot he app to do that.
So the API would look something like this:

```javascript
// in a blade
keybindingService.registerAction(actionId, actionDescription, actionCb);

// in the app
keybindingService.bindAction(actionId, shortcutKey);
keybindingService.bindAction(actionId);
```
