### ISSUE TITLE
Exception after creating app when there was a space in the path to the SDK

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1434]
I'm creating this issue after receiving an email from a developer about it.

> When I try to create a BR application, I get an error.

> ```
C:\Users\Colbert Philippe\workspace-luna-4.4.1-lottorally\BladeRunnerJS>brjs cre
ate-app brjstodo
creation of App at 'D:\bin\tools\BladeRunnerJS\sdk\ \brjs-apps\brjstodo' failed
Error:
  Cannot create application 'D:\bin\tools\BladeRunnerJS\sdk\ \brjs-apps\brjstodo    <= space inserted into path
'; java.io.IOException: Unable to create directory D:\bin\tools\BladeRunnerJS\sd
k\ \brjs-apps\brjstodo
Caused By:
  java.io.IOException: Unable to create directory D:\bin\tools\BladeRunnerJS\sdk
\ \brjs-apps\brjstodo
```

> As you can see, the error seems to be caused by the space inserted into the path.

> It should be easy to fix.

I've just tried to replicate with a freshly downloaded 1.0 RC1, but it actually worked for me:

```
dominicc@dominicc-laptop:~/Downloads/BladeRunner JS/sdk$ ./brjs create-app my-app
Problem:
  App 'my-app' already exists

Usage:
  brjs create-app <new-app-name> [<require-prefix>] [(-T|--template) <template-group>]
```

@thanhc or @thecapdan: can one of you try replicating this on Windows in case it's Windows specific please?


<!---
@huboard:{"order":1434.0,"milestone_order":1434,"custom_state":""}
-->

**Comment by germtb** [comment]
When I tried to reproduce this I found cygwin complaining about spaces, not java. 

`cygpath: error converting "test/sdk/../conf/java/*" - Unknown error -1`

When the actual path was:

`/cygdrive/c/brjs-2/brjs-sdk test/sdk/../conf/java/*`

I changed the part of the brjs script that calls cygwin and now it works. I am still trying to reproduce this issue.

**Comment by germtb** [comment]
Previously to the the changes in the brjs script (just the windows part), creating apps in paths with spaces and creating apps when the path of the sdk has spaces doesn't work. After the changes all of those worked so, if this is still an issue, I cannot reproduce it.
