### ISSUE TITLE
'themes' dirs in libs cause `request form name 'null' hasn't been registered` when building apps

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1443]
Any 'theme' dirs inside of libs cause an exception and prevent apps from being built.

The exception is caused because the `AssetPlugin` responsible for registering Assets inside of AssetContainers prefixes the require path for files inside of a `themes` directory with `theme!`. The `CSSResourceContentPlugin` then tries to turn this into an asset request but doesn't support requests for theme assets inside of a library.

Since we don't support themes inside of libs we should fix the `AssetPlugin` so it doesn't prefix the theme assets in libs.

**Comment by andyberry88** [comment]
Having looked at the tests it looks like we do support themes within libraries. So we don't break backwards compatibility I've changed the `cssresource` plugin to support requests for theme files. #1459 is the PR for this changed.

**Comment by thecapdan** [comment]
tested this with the it-app. fixed...

but, while testing i found i was getting a different error invoolving i18n token not found (even though they do exist):

```
Caused By:
  Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.


Stack Trace:
org.bladerunnerjs.api.model.exception.command.CommandOperationException: org.bladerunnerjs.api.model.exception.ModelOperationException: Error when trying to write the index page for 'apps/it-app/default-aspect/index.jsp'; Unable to find a replacement for the i18n key 'itapp.itbladeset.itblade.welcome-message'.
```

This is not a regression as a result of the work done for this task, so I'll merge this and open a new issue for the message above if necessary.
