### ISSUE TITLE
Editing index.html in an app corrupts the rendering

### ISSUE THREAD

**Issue by saifmd4u** [BladeRunnerJS/brjs#1452]
I have created an app using BRJS dashboard and then started modifying index.html. The page no longer renders correctly.

![image](https://cloud.githubusercontent.com/assets/2925798/8455388/2774c73a-1ffc-11e5-954b-c470c4cbc590.png)

I am using Visual Studio 2013 as my IDE. I have tried removing all my changes back to its original state but still has the same issue. I have tried opening that in notepad++ as well.

**Comment by andyberry88** [comment]
Thanks @saifmd4u, We'll take a look at this and get back to you. A few questions to help us debug this at our end:
- Does the app load OK before it's changed?
- Can you try creating a fresh app and only using notepad++ to modify it in case it's an issue caused by Visual Studio settings?
- Does Notepad++ tell you what encoding is being used for the file?
- What OS are you using? Are you using a particular character set or encoding?

**Comment by saifmd4u** [comment]
* Does the app load OK before it's changed?
*Yes*
* Can you try creating a fresh app and only using notepad++ to modify it in case it's an issue caused by Visual Studio settings?
*just using nodepad++ works*
* Does Notepad++ tell you what encoding is being used for the file?
*Notepad++ does not show any encodings*
* What OS are you using? Are you using a particular character set or encoding?
*Windows7-not specific encoding*

**Comment by saifmd4u** [comment]
I finally figured it out, if I save the file with the encoding format as "Western Europe (Windows) - Codepage 1252" it works.

![image](https://cloud.githubusercontent.com/assets/2925798/8457424/3387dd16-2009-11e5-94d7-00d3f53c2fe3.png)

so don't know what default enocding does BRJS use when creates files.

**Comment by andyberry88** [comment]
:+1: thanks for the update @saifmd4u.

When a new app is created the skeleton files are copied from `sdk/templates` and the same file encoding is used - this is likely to be `UTF-8`. If you want to use a different file encoding for files on disk you can change `defaultFileCharacterEncoding` in `conf/brjs.conf`. The file encoding used when generating content sent to the browser will always be `UTF-8`.

**Comment by andyberry88** [comment]
@saifmd4u I'd like to close this issue since it sounds like it's fixed. Is everything working OK for you now?

**Comment by saifmd4u** [comment]
Yes you could close the issue. Thanks for your help.
