### ISSUE TITLE
Warning about strict mode in IE*

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1453]
The locale forwarding page doesn't have a `DOCTYPE` so IE doesn't load in strict mode and BRJS shows an error. Going directly to a locale page works.

Seen using BRJS 1.0. There's no workaround to make the redirection page work - the only way to load the app is to go directly to the specific locale URL.

![upload](https://cloud.githubusercontent.com/assets/726896/8479704/5565fe04-20d1-11e5-971e-8e3196f54ade.png)

**Comment by andyberry88** [comment]
Fixed by #1454.

**Comment by thecapdan** [comment]
tested with the IT-app in IE9 - works now
