### ISSUE TITLE
create a sync-import Library

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1470]
Create a [sync-import](https://github.com/dchambers/sync-import) library that allows `System.import()` invocations to be synchronously resolved (needed by #1467). This library is probably already acceptable as is, and just needs to be promoted into the BladeRunnerJS namespace.

**Comment by dchambers** [comment]
@andyberry88, you happy for this to be moved to `ReadyForTest`?

**Comment by andyberry88** [comment]
:+1:

**Comment by thecapdan** [comment]
@dchambers is promoting this lib to the br namespace something that needs to be done as part of this issue, or at a later date?
