### ISSUE TITLE
Make our micro-libraries more like other Idiomatic JavaScript micro-libraries

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1481]
Here's a list of improvements to bring us more in line with standard practice these days:

  1. Use [karma](karma-runner.github.io/), [mocha](http://mochajs.org/) & [chai](http://chaijs.com/) instead of [jasmine](http://jasmine.github.io/) for testing.
  1. Use [browserify](http://browserify.org/) instead of [webbuilder](https://github.com/BladeRunnerJS/webbuilder) for building.
  1. Use [eslint](http://eslint.org/) for linting.
  1. Use [npm](https://www.npmjs.com/) instead of [Grunt](http://gruntjs.com/) as our build tool.
  1. Use standard directory names: `lib` -> `src`, `spec` -> `test` & `target` -> `dist`.
  1. Use `npm test` for running all tests, including a locally run browser test against Firefox, and SauceLab tests against various other browsers.
  1. Stop using [jsdoc](http://usejsdoc.org/), and use example driven `README.md` based documentation only.
  1. Stop creating [browser-modules](https://github.com/BladeRunnerJS/browser-modules) compatible distributions of our libraries, that even we don't use.
  1. Use a `master` branch instead of a `gh-pages` branch for simplicity, and get rid of the extra styling, and links to the different presentations of the exact same content.
  1. Use `:` as a delimiter to indicate sub-tasks.
  1. Stop using browser detection guards within code and tests, and instead let browserify provide a consistent environment.
  1. [Stop using Bower](https://gofore.com/ohjelmistokehitys/stop-using-bower/).

Additionally, we should provide a `npm run test:browser:debug` task that makes it easy for developers to debug the tests within a browser.

**Comment by dchambers** [comment]
This has now been done for [emitr](https://github.com/BladeRunnerJS/emitr).

**Comment by dchambers** [comment]
Although things are now much simpler than they were before, the release process is still too complicated, so I've created #1490 to help with this.

**Comment by dchambers** [comment]
@andyberry88, you happy for this to be moved to `ReadyForTest`?

**Comment by andyberry88** [comment]
:+1:

**Comment by andyberry88** [comment]
@dchambers is there a PR that updates the mico-libraries to the latest versions?

**Comment by dchambers** [comment]
@andyberry88, no, I just went ahead and made the changes in the `master` branches of the various projects. This is actually what we've always done, where the QA effort is used to confirm that it's safe to consume the changes within BRJS.

This is clearly not the right way of doing things, but is probably a consequence of the fact that it's not easy to manage sprints that involve multiple projects.

**Comment by andyberry88** [comment]
@dchambers We need a PR in BRJS to update each library to the latest version. Otherwise we just have a series of microlibraries that have changed but we're not making use of those changes in BRJS.

**Comment by dchambers** [comment]
Here are the relevant commits:

  * e049a2b1
  * 91d18c0
  * f911a36

all of which are long since merged into `master`.
