### ISSUE TITLE
Perform NPM Test Audit

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1482]
Perform a test audit where we determine all of the testing libraries we currently rely upon (for both BRJS & CT), and what the corresponding library will be once we convert to NPM. Additionally, where alternative libraries have to be used, we should indicate whether it might be possible to convert early in a BRJS 1.1.1 pre-release.

Once this audit has been completed, we should create additional breakout tasks for any extra work that will have to be done.

**Comment by dchambers** [comment]
Audit Results:

  1. [js-test-driver](https://code.google.com/p/js-test-driver/) -> [karma](karma-runner.github.io/) + [karma-jstd-adapter](https://www.npmjs.com/package/karma-jstd-adapter) (no change)
  1. [jasmine](http://jasmine.github.io/) -> [jasmine-node](https://github.com/mhevery/jasmine-node) (no change) **or** [mocha](http://mochajs.org/) + [expectations](https://github.com/spmason/expectations) (no change) **or** [mocha](http://mochajs.org/) + [chai](http://chaijs.com/api/assert/) + [Sinon.JS](http://sinonjs.org/)  (mostly automatable changes)

Lot's more to come...

**Comment by dchambers** [comment]
@andyberry88, do you think I've missed anything?

**Comment by andyberry88** [comment]
@dchambers  Not that I can think of. Looks good.

**Comment by dchambers** [comment]
I don't think this needs testing as such, so moving to done.
