### ISSUE TITLE
App deployed in tomcat root causes extra slash to appear in url

### ISSUE THREAD

**Issue by dogoku** [BladeRunnerJS/brjs#1487]
When deploying a brjs app in tomcat root requests made without a locale get redirected to a url with an extra slash.

E.g: Requesting http://domain.com, will redirect to http://domain.com//en

Requesting a url with a locale specified, no extra slash is added

If you require additional info let me know

**Comment by andyberry88** [comment]
@dchambers I'd suggest this is probably something we want to fix for 1.1. Thoughts?
