### ISSUE TITLE
Error pages cannot be accessed when BRJS is serving files

### ISSUE THREAD

**Issue by JamesSeymour** [BladeRunnerJS/brjs#1502]
In our web.xml we specify error pages as follows:

```
<error-page>
    <error-code>404</error-code>
    <location>/WEB-INF/error-pages/404.html</location>
</error-page>
```

When attempting to load page that doesn't exist it does not load the correct 404 error page, and you get the following error:

HTTP ERROR 404
Problem accessing /APPNAME/WEB-INF/error-pages/404.html. Reason:
    Not Found
Powered by Jetty://

This correctly works when a war is generated, but not using BRJS to serve.

**Comment by andyberry88** [comment]
This is fixed by #1503. The default servlet handles the error request and was always 404ing instead of using the server configured error pages.
