### ISSUE TITLE
Provide a `closure-medium` obfuscation setting

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1504]
We need a custom minification level (say `closure-medium`) between `closure-simple` and `closure-advanced`, that causes private members (i.e. members starting with `_` or `m_`) to be obfuscated. Over time, we might enable more settings if we can determine that it's safe to do so.

**Comment by dchambers** [comment]
I've done some work on this (see the [new-closure-obfuscation-setting branch](https://github.com/BladeRunnerJS/brjs/tree/new-closure-obfuscation-setting)), but I've discovered that it's dependent on an upstream change to Google Closure as a pre-requisite, so won't be able to progress it further until/if I manage to get my pull-request accepted.

**Comment by dchambers** [comment]
Marking this as a high-priority issue since it's blocking our ability to make some of our demo apps available publicly.

**Comment by andyberry88** [comment]
@dchambers if this is needed ASAP we could build our own version of the closure compiler and host it at https://github.com/BladeRunnerJS/brjs-build-dependencies. Make sure to add a `-brjs` to the artefact name though so we know its a custom built version.

**Comment by dchambers** [comment]
Okay, that's a really good back-up plan. I think we're nearing a conclusion on how this can be done in a way that would be acceptable to merge upstream, so will wait till I hear more before I do anything.

**Comment by andyberry88** [comment]
So we don't loose track of the whole story https://github.com/google/closure-compiler/pull/1087 is the (unmerged) PR for the Google closure project.

**Comment by dchambers** [comment]
> So we don't loose track of the whole story google/closure-compiler#1087 is the (unmerged) PR for the Google closure project.

This is now available in:

  * https://github.com/google/closure-compiler/pull/1129

**Comment by andyberry88** [comment]
https://github.com/BladeRunnerJS/brjs/pull/1524 is the PR for the BRJS changes required for this.

**Comment by dchambers** [comment]
**Problem:**

There is widespread use of the following methods in _presenter_:

  * `Property.addChangeListener(oListener, sMethod, bNotifyImmediately)`
  * `Property.addUpdateListener(oListener, sMethod, bNotifyImmediately)`
  * `EditableProperty.addValidationErrorListener(oListener, sMethod, bNotifyImmediately)`
  * `EditableProperty.addValidationSuccessListener(oListener, sMethod, bNotifyImmediately)`
  * `EditableProperty.addValidationCompleteListener(oListener, sMethod, bNotifyImmediately)`

which aren't currently Closure Compatible since the `sMethod` parameters are string representations of private methods that will be ofuscated by Closure Compiler.

**Solution:**

We could solve this by changing the names of call-back methods (e.g. `_buttonClick`) so that they are no longer recognized as private methods, but are still distinguishable from public methods by the developer (e.g. `$buttonClick`).

Or, alternatively, we could support an alternate call signature for these methods, so that in addition to `addXXXListener(oListener, sMethod, bNotifyImmediately)` we also support `addXXXListener(fCallback, bNotifyImmediately)`, allowing code like this:

```js
this.button.addChangeListener(this, '_buttonClick');
```

to be changed to this:

```js
this.button.addChangeListener(this._buttonClick.bind(this));
```

where the second proposal has the advantage that far more of our code will end up being obfuscated.

**Comment by dchambers** [comment]
Another block I've discovered is the `PresentationNode.isPrivateKey()` method, because:

  1. It's not able to determine which methods are private once the code has been obfuscated.
  1. We could change Closure Compiler to prepend an `_` prefix to renamed properties, but this would mean we'd be permanently stuck on our fork of Closure Compiler, and that download sizes would be marginally bigger. 
  1. Although we could encourage people to hide their properties within closures rather than relying on naming, this would still lead to differences between development and production since:
    1. Private properties would no longer be recognized as such in production.
    2. Public properties might be incorrectly recognized as private properties if `closure-advanced` is used **and** if a property is renamed so that it starts with an `_` or `m_`.

If we don't want to permanently fork Closure Compiler, than it makes sense to use a deprecation-flag to allow the functionality within `isPrivate()` to be disabled, so that things work the same in _dev_ and _production_.
