### ISSUE TITLE
css resources referenced by libs not being bundled in the WAR

### ISSUE THREAD

**Issue by sospirited** [BladeRunnerJS/brjs#1512]
Noticed this issue as part of going from a pre-1.0 version of BRJS to the latest.

Relevant files on disk:
1) `<app>/libs/mylibrary/loginscreen/style.css`
```
background-image: url('images/login-title.png');
```
2) `<app>/libs/mylibrary/loginscreen/images/login-title.png`
3) `<app>/libs/mylibrary/thirdparty-lib.manifest`
```
depends: css-reset
css: "**/*.css"
exports: null
```
4) `<app>/login-aspect/index.html`
```
<script>
  br.Core.thirdparty('mylibrary');
</script>
```

The above works fine in BRJS but when the war is built:
`brjs build-app <app> -w`

Then I do not see the following resource in the WAR:
`<warFile>/login/v/<number>/cssresource/lib_mylibrary/loginscreen/images/login-title.png`

Things to note:
- non-default aspect is used
- the theme css file is from a subfolder
- the referenced image is in a subfolder relative to the css file
- works in BRJS dev mode, not in the WAR
- workaround of moving the login-tile to be parallel to the style.css file leads to the image being bundled so there definitely seems to be an issue with the subfolder?

**Comment by andyberry88** [comment]
So the underling bug here was the require paths for Thirdparty lib directories weren't being calculated so they were unique enough. This meant that having 2 directories called `images`, e.g. `foo/bar/images` and `some/dir/images` both had the same require path and one wasn't picked up in the dependency analysis process properly and ultimate deemed to not exist when working out if assets were used.

#1519 fixes this and also adds a number of tests to ensure that we bundle most types of common image formats whether they are used or not (something we'd supported beforehand anyway but had few tests around).

**Comment by thecapdan** [comment]
managed to reproduce the image. the fix works. tests have been reviewed. done
