### ISSUE TITLE
Java 8u60 issue

### ISSUE THREAD

**Issue by SeKu2** [BladeRunnerJS/brjs#1539]
After java updated to 8u60 brjs.cmd gives this:
> Error occurred during initialization of VM
> java/lang/NoClassDefFoundError: java/lang/Object
>
> Process finished with exit code 1

**Comment by SeKu2** [comment]
Found out it's java issue itself. Not brjs related. Sorry for that.

**Comment by andyberry88** [comment]
@SeKu2 can you elaborate on what the issue with Java was in case anyone else has the same issue?

**Comment by SeKu2** [comment]
Seems just like updating java to 8u60 wasn't successful. So after system rebooted the java itself was missing some core parts and couldn't be run at all. After installing java 8u60 by myself jre works again, so the brjs.

**Comment by andyberry88** [comment]
:+1: Thanks @SeKu2.
