### ISSUE TITLE
create tests that exercise the fell/topiarist/emitr APIs

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1547]
we need some tests that exercise the whole API of each of our microlibraries to prevent backwards compatibility issues in future.

**Comment by dchambers** [comment]
@andyberry88, I don't understand the acceptance criteria for this issue. Also, I'm not sure why this has gone ahead of all the bug & docs issues that prior to you creating this `2.0.0` milestone where what we were focussed on doing next.

So, I guess the question is, why have we created a `2.0.0` milestone at all?

**Comment by dchambers** [comment]
@andyberry88, this issues seems to be pointless without first starting to run the `it-app` tests using the `test-integration` command. Is that correct, and do you know if we have an issue for that task?

**Comment by andyberry88** [comment]
>  this issues seems to be pointless without first starting to run the 'it-app' tests using the test-integration command

Yep, true. I've suggested to @hobojed makes sure the tests are run via the build and in CI.

**Comment by hobojed** [comment]
@dchambers, I've updated the build run the UTs and ATs, but the ITs seem to require Java 6 to run, so they have been pulled out into another task.

I was intending to us the UT framework to write the backwards compatibility tests, as I think that would be the simplest way to get the coverage we want.
