### ISSUE TITLE
On bundled code, remove newline from the wrapping function

### ISSUE THREAD

**Issue by trueadm** [BladeRunnerJS/brjs#1567]
Currently, BRJS adds this line to the top of each file/module:

`define('module', function(require, exports, module) {`

The problem is that this pushes the line number off by one and this has a detrimental affect on code that relies on sourcemaps. I'm sure this is as simple as removing the new line character from the appended wrapping function.

**Comment by andyberry88** [comment]
While I think this is a good idea to do we should probably remember the reason (if there is one) why we decided to add the newline in the first place. I doubt there is any reason behind it but just in the off chance that there is something.

**Comment by trueadm** [comment]
@dchambers had an explanation but said that in the case of sourcemaps it makes sense to remove the new line so debugging has some sanity again.

**Comment by andyberry88** [comment]
It would be worth adding the explanation here (@dchambers) so at least its captured in case we forget the reasoning in future. I'd agree, it does make sense to get rid of it. I guess we could always make it configurable if it's going to cause huge issues, although my preference would probably be to just remove the extra line.
