### ISSUE TITLE
Implement jasmine-clock

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1592]
Implement [jasmine-clock](https://github.com/BladeRunnerJS/jasmine-clock).

**Comment by dchambers** [comment]
@andyberry88, I think jasmine-sinon-clock should be renamed to jasmine-clock as what it depends on internally is an implementation detail only.

**Comment by thecapdan** [comment]
a few issues:

1. doesn't have a travis build(?)
2. tests are failing on firefox (Uncaught ReferenceError: setImmediate is not defined)
3. it has a lot of linting errors. run the lint script to see them

**Comment by dchambers** [comment]
> 1. doesn't have a travis build(?)

or a Travis build indicator.

**Comment by andyberry88** [comment]
All issues above now fixed :smile:

**Comment by dchambers** [comment]
> All issues above now fixed :smile:

He he, your Travis build indicator points to the BRJS build ... school boy error! :smiley:

**Comment by andyberry88** [comment]
> school boy error!

Very school boy error! Serves me right for copying and pasting!

**Comment by dchambers** [comment]
All looks good :+1:
