### ISSUE TITLE
Decision: Choose an NPM Integration Strategy

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1610]
We were originally going to integrate with NPM based on the [BladeRunnerJS NPM Integration Strawman](https://github.com/BladeRunnerJS/brjs/wiki/BladeRunnerJS-NPM-Integration-Strawman), which involved doing our bundling and using [SystemJS](https://github.com/systemjs/systemjs) as our module format. Then, we subsequently came to the conclusion that we could more quickly get something out there by relying on a third-party bundler to bundle a script that caused the various parts of the bundle to be made available via our current module system ([browser-modules](https://github.com/BladeRunnerJS/browser-modules)), as per the [Alternative NPM Integration Strawman](https://github.com/BladeRunnerJS/brjs/wiki/Alternative-NPM-Integration-Strawman).

Unfortunately, this approach means that clients that don't want to or can't use NPM would be forced to bundle every part of every BRJS and CT library, effectively creating a hard dependency on Node.js since this is unlikely to be acceptable to anyone. While we could go back to the original approach, we've since realized that the alternate approach has some other advantages that are worth taking into consideration before we make a decision.

Here are the pertinent facts...

**Bundle ourselves:**
  1. No hard dependency on Node.js.
  1. Can only use System.js.
  1. No source maps.
  1. Requires more time (though we have a BRJS / SystemJS spike so some of the additional work is now done).
  1. System.js is a sizable dependency (additional 17.5KB when minified and gzipped &mdash; see these [two](https://github.com/BladeRunnerJS/brjs/issues/1389#issuecomment-106784621) [comments](https://github.com/BladeRunnerJS/brjs/issues/1389#issuecomment-109974353)).
  1. No slower than current bundling.

**Use external bundler:**
  1. Hard dependency on Node.js.
  1. Can use any bundler.
  1. Can use sourcemaps.
  1. Quicker to implement.
  1. Modules from Node.js bundle have to be re-exported using `define()` invocations, which adds additional size.
  1. Maybe slower because there are two bundlers, one of which requires a process to be spawned (e.g. ~1sec to bundle [react](https://github.com/facebook/react) & [redux](https://github.com/rackt/redux) &mdash; use the [bundle-all-spike](https://github.com/BladeRunnerJS/bundle-all-spike) to calculate your own figures).

So, which option would people prefer us to go with?

**UPDATE:** @trueadm suggested a third option which is better than the previous two. The idea here is to convert NPM libraries into a form that BRJS can already consume. Exactly how this would be done, and whether this can be done in a way that would still allow CSS and HTML templates to be required, etc, is still to be determined, but it seems like a promising idea.

**Use NPM to BRJS conversion tool:**

  1. No dependency on Node.js
  1. No bundler required.
  1. No sourcemap support.
  1. Quick to implement.
  1. No change to the bundled size.
  1. No change to the bundle creation speed.

**Comment by trueadm** [comment]
Personally, I'd much prefer to use *an external bundler*.

**Comment by dchambers** [comment]
Assuming it can be made to work, we've decided to go with #1611 since it has no downsides, but still allows us to start migrating our libraries to NPM.
