### ISSUE TITLE
LocalisedAmountParser should not parse values with decimals with trailing zeroes

### ISSUE THREAD

**Issue by Shikaga** [BladeRunnerJS/brjs#1626]
We are having an issue where a customer is trying to type "123.05" into an amount field, but as soon as they enter "123.0", it gets parsed into "123". We think it would better not to parse values with trailing decimals. In fact, we think it would be best not parse a value, until it has a modifier such as "K" or "M" on it.

**Comment by dchambers** [comment]
Agreed, moved to `ReadyForTest`. Thanks @Shikaga.

**Comment by thecapdan** [comment]
This will cause problems for other teams user libraries, @Shikaga has agree that we should revert this change
