### ISSUE TITLE
use Laravel's Flysystem to get/put assets

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1634]
We need to remove Rackspace's OpenCloud library and use the Laravel Flysystem
- BONUS: use Rackspace directly rather than going via Laravel to access files. 
  - How do we do auth?

**Comment by thecapdan** [comment]
hi @andyberry88 we have had all available resources working on this for the last 8 days, we pulled in some devs from other teams and cancelled a few projects... I think we finally have it done. Are you ready to test?

**Comment by andyberry88** [comment]
:dizzy_face:  DAMMIT!! Wrong project. I think you should remove me from the BRJS organisation so I don't get confused again in the future. :smile:
