### ISSUE TITLE
Libraries with same prefix overshadows translation keys

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1714]
When two libraries have the same requirePrefix inside br-lib.conf only one of the i18n files of them gets bundled. This was not an issue before so it looks like a bug of the new version of brjs/ct.

PCTLIBRARY-1846

**Comment by thecapdan** [comment]
Closing this issue. As a workaround one could place i18n tokens at the aspect level or give one of the libaries a different name.

The originator of this issue will no longer have this issue when they move over to the next version of CT.
