### ISSUE TITLE
As a developer, when my require() fails, I want to know the locations BRJS attempted to find my dependency

### ISSUE THREAD

**Issue by sospirited** [BladeRunnerJS/brjs#565]
There are multiple locations/scopes from where dependencies can be required.
E.g.
- sdk/libs/javascript/br-libs
- sdk/libs/javascript/thirdparty
- `<appName>`/default-aspect/src/
- `<appName>`/`<myBladeset>`/`<myBlade>`/src
- `<appName>`/libs
etc

This will help developers better understand why certain items aren't being bundled when invalid requirePaths are made (e.g. bladesets trying to require a blade class)

If we're failing fast anyway, the above information would make for such a richer debugging experience and reduce dev frustration!

**Comment by dchambers** [comment]
This issue will probably be best fixed by using @janhancic's proposal in #1232.

**Comment by dchambers** [comment]
Fixed by #1291.

**Comment by ccpetercc** [comment]
For #1291:
Also need to add a message saying which file the guilty require appears in

**Comment by andyberry88** [comment]
#1318 is now the PR for this. I've taken most of the changes from #1291. applied them on top of the API changes in #1277 and then built on top of it for the extra scope enforcement in #1232.

**Comment by andyberry88** [comment]
While there are some issues relating to #1232 this particular issue has been fixed in #1318 and IMO can be closed once that is merged.
