### ISSUE TITLE
Blade's resources are not bundled if blade has no code

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs#597]
If I have a blade that has no JS code, but only some XML configuration (for grid), the XML of that blade is not bundled.

**Comment by dchambers** [comment]
@thecapdan, can you verify this works for XML, HTML & I18N. @hobojed thinks this isn't working for HTML.

**Comment by thecapdan** [comment]
Verified. created  i18n only and html only blades. both work doing the following in App.js to insert both:

```
function App() {
//i18n only
	var i18n = require("br/I18n");
	var element = document.getElementById('hello-world');
	var lovelyMessage= i18n('my.i18nblade.lovely.message');
	element.innerHTML = lovelyMessage;

//html only
	var myTemplate = require('service!br.html-service').getTemplateElement("my.htmlonly.blade.view-template");
	element.appendChild(myTemplate);
}
```
both work. + fxtrader has xml only blades which work

**Comment by dchambers** [comment]
Good work :+1:, thanks @thecapdan.
