### ISSUE TITLE
Index Pages Should Have Proper require() Support

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#720]
At the moment index pages are using a trie to find dependencies, but it would be preferable to also use the same `require()` scanning we use for CommonJs classes. This will enable better feedback to developers that attempt to use an incorrect _require-path_.

**Comment by andyberry88** [comment]
I agree with @janhancic on this one. This previously wasn't much of an issue but since we've started encouraging developers to 'require' services this is now broken.

**Comment by ioanalianabalas** [comment]
Fixed by #1179.

**Comment by ioanalianabalas** [comment]
Closing in favour of #1188.
