### ISSUE TITLE
allow the use of tokens when exporting to static files

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#749]
allow tokens to be provided either via JNDI lookup or properties files. fail if no lookup is found for static apps since JNDI look up is never possible, with J2EE apps fail if tokens are not found via JNDI lookup and warn if not found through properties files.
properties should always be read from `default.properties` and then be overridden by a specific 'environment' file supplied by using the `-e` flag. the same flag (and mechanism) should be supported by both `serve` and `build` commands.

**Comment by dchambers** [comment]
@andyberry88, can we have some acceptance criteria around:

  1. Which properties file will be used when running `brjs serve` (presumably `dev.properties`)?
  1. How we will know whether to use a properties file or to expect this stuff to be defined via JNDI?
  1. How `brjs build` will allow the dev to switch properties.
  1. Whether there are any other commands that will need the ability to switch properties files (e.g. `brjs test` or even `brjs serve`).
  1. Whether the property switching flag might actually be a global flag?

**Comment by thecapdan** [comment]
can we update the description for this with the acceptance criteria that came out during various conversations? thanks

**Comment by andyberry88** [comment]
@thecapdan updated.

**Comment by thecapdan** [comment]
fixed by https://github.com/BladeRunnerJS/brjs/pull/1483
