### ISSUE TITLE
CommonJs Support Rough Edges

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#883]
Although CommonJS can already be used, there are a number of rough edges that need to be fixed before we can really say that it Just Works(TM):

  -  [x] #850
  -  [x] #482
  -  [x] #604
  -  [x] #782
  -  [x] #422
  -  [x] #1050
  -  [ ] #424 (to reduce the need for the work-around described in #1050)

**Comment by andyberry88** [comment]
Given this is largely done (only #424 remains) and it's just adding noise now I'm going to close it.
