### ISSUE TITLE
Locale redirection doesn't work in built app when deployed using Apache Cordova

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#923]
@soruban has found that, when using Apache Cordova, 'index.html' redirects to the wrong URL in the exported app because the `host` variable within that page contains an unneeded slash. I've asked @jngo00 to provide details about the value of `host` when using Apache Cordova.

**Comment by ioanalianabalas** [comment]
Fixed by #1193.

@jngo00 will be testing it later today to confirm that it is working for them.
