### ISSUE TITLE
Our build is really slow on Windows

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#932]
On Windows we are seeing build times of over 7 minutes on the same spec machine where we see 2 to 3 minute build times on Linux. This is negatively affecting the productivity of the QAs (who use Windows), but not the developers (who all use UNIX), and should be fixed. It may or may not be related to #931.

**Comment by ioanalianabalas** [comment]
The build ran:

With FileWatcher: 5 mins 2.749 secs
Without FileWatcher: 4 mins 29.871 secs

**Comment by ioanalianabalas** [comment]
@dchambers and I have established that in order to locate which tests take the longest time to run, we will be running them as separate tasks, rather than the whole build. So we are looking at:

- Java tests
- Javascript tests
- Assemble without JSDoc
- JSDoc

Additionally, we will be looking at excluding the tasks `:brjs-sdk:copyBrowsers` and `:brjs-sdk:createSdkJsDocs` when running the assemble/tests.

**Comment by dchambers** [comment]
Using the 0.15.1 branch (`git checkout v0.15.1`), from `BRJS_ROOT` run these tests:

```bash
gradle clean testJava
gradle clean assemble -x :brjs-sdk:copyBrowsers -x :brjs-sdk:createSdkJsDocs
gradle clean :brjs-sdk:copyBrowsers
gradle clean :brjs-sdk:createSdkJsDocs
```

and from `BRJS_ROOT/brjs-sdk/sdk` run this test:

```bash
./brjs test libs/
```

**Comment by andyberry88** [comment]
I did some work on this issue in https://github.com/BladeRunnerJS/brjs/pull/1277 so the build doesn't re-run things like the doc tasks when it doesn't need to. It might be worth doing the same test in that branch.

**Comment by ioanalianabalas** [comment]
Windows:
`gradle clean testJava`: 2 mins 21.111 secs
`gradle clean :brjs-sdk:copyBrowsers`: 12.767 secs
`gradle clean :brjs-sdk:createSdkJsDocs`: 58.4 secs
`gradle clean assemble -x :brjs-sdk:copyBrowsers -x :brjs-sdk:createSdkJsDocs`: 46.533 secs
`gradle clean assemble -x :brjs-sdk:createSdkJsDocs`: 42.019 secs

`time ./brjs test libs/`: 
real    0m4.791s
user    0m0.255s
sys     0m0.244s

**Comment by dchambers** [comment]
@andyberry88, we're trying to find what's causing the slow-down at this point, rather than trying to fix the slow-down.

**Comment by dchambers** [comment]
Linux:
`gradle clean testJava`: 1 mins 32.961 secs
`gradle clean :brjs-sdk:copyBrowsers`: 10.737 secs
`gradle clean :brjs-sdk:createSdkJsDocs`: 1 mins 2.344 secs
`gradle clean assemble -x :brjs-sdk:copyBrowsers -x :brjs-sdk:createSdkJsDocs`: 32.572 secs

`time ./brjs test libs/`: 
real	0m48.365s
user	1m7.722s
sys	0m3.335s

**Comment by dchambers** [comment]
@andyberry88, we're trying to find what's causing the slow-down at this point, rather than trying to fix the slow-down.

**Comment by ioanalianabalas** [comment]
Tests on FxTrader motif: 4m54sec.

**Comment by dchambers** [comment]
Tests on FxTrader motif: 5m48.135s (**LInux**).

**Comment by dchambers** [comment]
Time between clicking login on FxTrader Motif and seeing the 'Unable to establish streaming connection' message:

~9.5s (Initial Load)
~1.5s (Subsequent Load)

I ran these tests three times since it's just crude stopwatch test.

**Comment by ioanalianabalas** [comment]
~10,69s (Initial Load)
~1.7s (Subsequent Load)

**Comment by dchambers** [comment]
This investigation has shown that BRJS is no longer slower on Windows, even though a myth that that is still slower has continued to persist &mdash; It did used to be slower when we had the file watcher service constantly enabled, but since we've only enabled that for `brjs serve` this has no longer been the case.
